package openai

import "github.com/ai-volund/volund/internal/llm"

const ProviderName = "openai"

// knownModels is the Volund catalog of supported OpenAI models.
// Prices are USD per 1M tokens as of Q1 2025.
var knownModels = []*llm.ModelInfo{
	{
		Provider:           ProviderName,
		ID:                 "gpt-4o",
		DisplayName:        "GPT-4o",
		ContextWindow:      128_000,
		MaxOutputTokens:    16_384,
		SupportsVision:     true,
		SupportsToolUse:    true,
		SupportsStreaming:   true,
		InputPricePerMTok:  2.50,
		OutputPricePerMTok: 10.00,
	},
	{
		Provider:           ProviderName,
		ID:                 "gpt-4o-mini",
		DisplayName:        "GPT-4o Mini",
		ContextWindow:      128_000,
		MaxOutputTokens:    16_384,
		SupportsVision:     true,
		SupportsToolUse:    true,
		SupportsStreaming:   true,
		InputPricePerMTok:  0.15,
		OutputPricePerMTok: 0.60,
	},
	{
		Provider:           ProviderName,
		ID:                 "gpt-4.1",
		DisplayName:        "GPT-4.1",
		ContextWindow:      1_047_576,
		MaxOutputTokens:    32_768,
		SupportsVision:     true,
		SupportsToolUse:    true,
		SupportsStreaming:   true,
		InputPricePerMTok:  2.00,
		OutputPricePerMTok: 8.00,
	},
	{
		Provider:           ProviderName,
		ID:                 "gpt-4.1-mini",
		DisplayName:        "GPT-4.1 Mini",
		ContextWindow:      1_047_576,
		MaxOutputTokens:    32_768,
		SupportsVision:     true,
		SupportsToolUse:    true,
		SupportsStreaming:   true,
		InputPricePerMTok:  0.40,
		OutputPricePerMTok: 1.60,
	},
	{
		Provider:           ProviderName,
		ID:                 "o1",
		DisplayName:        "o1",
		ContextWindow:      200_000,
		MaxOutputTokens:    100_000,
		SupportsVision:     true,
		SupportsToolUse:    true,
		SupportsStreaming:   false,
		InputPricePerMTok:  15.00,
		OutputPricePerMTok: 60.00,
	},
	{
		Provider:           ProviderName,
		ID:                 "o3",
		DisplayName:        "o3",
		ContextWindow:      200_000,
		MaxOutputTokens:    100_000,
		SupportsVision:     true,
		SupportsToolUse:    true,
		SupportsStreaming:   false,
		InputPricePerMTok:  10.00,
		OutputPricePerMTok: 40.00,
	},
	{
		Provider:           ProviderName,
		ID:                 "o3-mini",
		DisplayName:        "o3 Mini",
		ContextWindow:      200_000,
		MaxOutputTokens:    100_000,
		SupportsVision:     false,
		SupportsToolUse:    true,
		SupportsStreaming:   false,
		InputPricePerMTok:  1.10,
		OutputPricePerMTok: 4.40,
	},
	{
		Provider:           ProviderName,
		ID:                 "o4-mini",
		DisplayName:        "o4 Mini",
		ContextWindow:      200_000,
		MaxOutputTokens:    100_000,
		SupportsVision:     true,
		SupportsToolUse:    true,
		SupportsStreaming:   false,
		InputPricePerMTok:  1.10,
		OutputPricePerMTok: 4.40,
	},
	{
		Provider:           ProviderName,
		ID:                 "text-embedding-3-small",
		DisplayName:        "Text Embedding 3 Small",
		ContextWindow:      8_191,
		MaxOutputTokens:    0,
		SupportsVision:     false,
		SupportsToolUse:    false,
		SupportsStreaming:   false,
		InputPricePerMTok:  0.02,
		OutputPricePerMTok: 0,
	},
	{
		Provider:           ProviderName,
		ID:                 "text-embedding-3-large",
		DisplayName:        "Text Embedding 3 Large",
		ContextWindow:      8_191,
		MaxOutputTokens:    0,
		SupportsVision:     false,
		SupportsToolUse:    false,
		SupportsStreaming:   false,
		InputPricePerMTok:  0.13,
		OutputPricePerMTok: 0,
	},
}
